# Netlify configuration for True Religion Of Zion
# Builds the Vite app and ensures client-side routing works.
# If your project files live in a subfolder, keep the base line below.
# If you later move the files to the repo root, delete the base line.

[build]
  base = "true-religion-of-zion"
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
